# 3DDFA_V2 ONNX paths relative to this file's directory.
arch: resnet22
resnet_onnx: ../resnet22.onnx
faceboxesprod_onnx: ../FaceBoxesProd.onnx
param_mean_std: param_mean_std_62d_120x120.pkl
size: 120
num_params: 62
