"""Add tus_upload_id to photos

Revision ID: 348cce618932
Revises: add_unique_photographers_phone
Create Date: 2026-09-06 19:42:32.499838

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348cce618932'
down_revision: Union[str, None] = 'add_unique_photographers_phone'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('tus_upload_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_photos_tus_upload_id'), 'photos', ['tus_upload_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_tus_upload_id'), table_name='photos')
    op.drop_column('photos', 'tus_upload_id')
    # ### end Alembic commands ###
