"""Add proxy file size bytes

Revision ID: 7577bc03e82a
Revises: add_shared_with_guests
Create Date: 2026-09-16 16:57:42.164613

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7577bc03e82a'
down_revision: Union[str, None] = 'add_shared_with_guests'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('proxy_file_size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.drop_index(op.f('idx_photos_event_shared'), table_name='photos', postgresql_where='(shared_with_guests IS TRUE)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_photos_event_shared'), 'photos', ['event_id'], unique=False, postgresql_where='(shared_with_guests IS TRUE)')
    op.drop_column('photos', 'proxy_file_size_bytes')
    # ### end Alembic commands ###
